### ISSUE TITLE
how can I draw a half circle?

### ISSUE THREAD

**Issue by DorisOu** [s-yadav/radialIndicator#13] opened 2016-10-10 08:32 UTC
pls help me to check the bellow image. I would like to draw a half circle just like the bellow image.

![image](https://cloud.githubusercontent.com/assets/20514249/19230432/00b2674e-8f07-11e6-88bf-2f1ceb26b9bf.png)

**Comment by s-yadav** [comment] 2016-10-13 03:48
Duplicate of #15

**Closed by s-yadav** 2016-10-13 03:48 UTC
Labels: duplicate
